[platformio]
default_envs = node1, node2, node3

; NODE 1 - ESP32 + Rain Sensor (COM5)
[env:node1]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM5
monitor_port = COM5
monitor_speed = 115200
lib_deps = 
    bblanchon/ArduinoJson@^6.21.3
build_flags = 
    -D NODE_ID=1
    -D NODE_TYPE='"RAIN_SENSOR"'
build_src_filter = +<node1.cpp>

; NODE 2 - ESP32 + HC-SR04 (COM7) 
[env:node2]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM7
monitor_port = COM7
monitor_speed = 115200
lib_deps = 
    bblanchon/ArduinoJson@^6.21.3
build_flags = 
    -D NODE_ID=2
    -D NODE_TYPE='"ULTRASONIC"'
build_src_filter = +<node2.cpp>

; NODE 3 - ESP32 + Buzzer + ThingsBoard (COM3) 
[env:node3]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM3
monitor_port = COM3
monitor_speed = 115200
lib_deps = 
    bblanchon/ArduinoJson@^6.21.3
    knolleary/PubSubClient@^2.8
build_flags = 
    -D NODE_ID=3
    -D NODE_TYPE='"GATEWAY"'
build_src_filter = +<node3.cpp>